
import { Language, Subject, Difficulty } from './types';

export const UI_STRINGS: Record<Language, any> = {
  en: {
    appName: 'Quiz X.ai',
    tagline: 'Master your subjects with AI-powered quizzes',
    startQuiz: 'Start Quiz',
    selectLanguage: 'Select Language',
    selectSubject: 'Select Subject',
    selectDifficulty: 'Select Difficulty',
    mathematics: 'Mathematics',
    physics: 'Physics',
    chemistry: 'Chemistry',
    biology: 'Biology',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    next: 'Next',
    previous: 'Previous',
    finish: 'Finish',
    score: 'Score',
    timeRemaining: 'Time Remaining',
    explanation: 'Explanation',
    correct: 'Correct',
    incorrect: 'Incorrect',
    quizComplete: 'Quiz Complete!',
    backToHome: 'Back to Home',
    history: 'Quiz History',
    stats: 'Performance Stats',
    noHistory: 'No quizzes taken yet. Start learning!',
    generating: 'Generating your AI Quiz...',
    loadingMessage: 'Our AI is crafting specialized questions for you...',
    points: 'Points',
    accuracy: 'Accuracy',
    share: 'Share Results',
    downloadCertificate: 'Download Certificate',
    retry: 'Retry Quiz',
    generateCard: 'Generate AI Certificate',
    generatingCard: 'Creating your certificate...',
    cardReady: 'Your certificate is ready!',
    downloadPNG: 'Download PNG',
    downloadPDF: 'Download PDF',
    saveScoreCTA: 'Sign up to save this score permanently',
    scoreSaved: 'Score saved to your profile!',
    limitReached: 'Weekly limit reached',
    limitDescription: 'Free users can generate 3 quizzes per week.',
    upgradePro: 'Upgrade to Pro for unlimited quizzes',
    quizzesRemaining: 'Quizzes remaining this week',
    monthly: 'Monthly',
    annually: 'Annually',
    bestValue: 'Best Value',
    subscribe: 'Subscribe Now'
  },
  km: {
    appName: 'Quiz X.ai',
    tagline: 'ស្ទាត់ជំនាញមុខវិជ្ជារបស់អ្នកជាមួយកម្រងសំណួរ AI',
    startQuiz: 'ចាប់ផ្តើមកម្រងសំណួរ',
    selectLanguage: 'ជ្រើសរើសភាសា',
    selectSubject: 'ជ្រើសរើសមុខវិជ្ជា',
    selectDifficulty: 'ជ្រើសរើសកម្រិតលំបាក',
    mathematics: 'គណិតវិទ្យា',
    physics: 'រូបវិទ្យា',
    chemistry: 'គីមីវិទ្យា',
    biology: 'ជីវវិទ្យា',
    easy: 'ងាយស្រួល',
    medium: 'មធ្យម',
    hard: 'ពិបាក',
    next: 'បន្ទាប់',
    previous: 'ថយក្រោយ',
    finish: 'បញ្ចប់',
    score: 'ពិន្ទុ',
    timeRemaining: 'ពេលវេលានៅសល់',
    explanation: 'ការពន្យល់',
    correct: 'ត្រឹមត្រូវ',
    incorrect: 'មិនត្រឹមត្រូវ',
    quizComplete: 'បានបញ្ចប់កម្រងសំណួរ!',
    backToHome: 'ត្រឡប់ទៅផ្ទះវិញ',
    history: 'ប្រវត្តិកម្រងសំណួរ',
    stats: 'ស្ថិតិការអនុវត្ត',
    noHistory: 'មិនទាន់មានកម្រងសំណួរទេ។ ចាប់ផ្តើមរៀន!',
    generating: 'កំពុងបង្កើតកម្រងសំណួរ AI របស់អ្នក...',
    loadingMessage: 'AI របស់យើងកំពុងរៀបចំសំណួរពិសេសសម្រាប់អ្នក...',
    points: 'ពិន្ទុ',
    accuracy: 'ភាពត្រឹមត្រូវ',
    share: 'ចែករំលែកលទ្ធផល',
    downloadCertificate: 'ទាញយកវិញ្ញាបនបត្រ',
    retry: 'ធ្វើកម្រងសំណួរឡើងវិញ',
    generateCard: 'បង្កើតវិញ្ញាបនបត្រ AI',
    generatingCard: 'កំពុងបង្កើតវិញ្ញាបនបត្រ...',
    cardReady: 'វិញ្ញាបនបត្ររបស់អ្នករួចរាល់ហើយ!',
    downloadPNG: 'ទាញយក PNG',
    downloadPDF: 'ទាញយក PDF',
    saveScoreCTA: 'ចុះឈ្មោះដើម្បីរក្សាទុកពិន្ទុនេះជាអចិន្ត្រៃយ៍',
    scoreSaved: 'ពិន្ទុត្រូវបានរក្សាទុកក្នុងប្រវត្តិរូបរបស់អ្នក!',
    limitReached: 'ឈានដល់ដែនកំណត់ប្រចាំសប្តាហ៍',
    limitDescription: 'អ្នកប្រើប្រាស់ឥតគិតថ្លៃអាចបង្កើតកម្រងសំណួរចំនួន 3 ក្នុងមួយសប្តាហ៍។',
    upgradePro: 'ដំឡើងទៅ Pro សម្រាប់កម្រងសំណួរមិនកំណត់',
    quizzesRemaining: 'កម្រងសំណួរនៅសល់ក្នុងសប្តាហ៍នេះ',
    monthly: 'ប្រចាំខែ',
    annually: 'ប្រចាំឆ្នាំ',
    bestValue: 'តម្លៃល្អបំផុត',
    subscribe: 'ជាវឥឡូវនេះ'
  },
  th: {
    appName: 'Quiz X.ai',
    tagline: 'เก่งในวิชาของคุณด้วยควิซพลัง AI',
    startQuiz: 'เริ่มทำควิซ',
    selectLanguage: 'เลือกภาษา',
    selectSubject: 'เลือกวิชา',
    selectDifficulty: 'เลือกระดับความยาก',
    mathematics: 'คณิตศาสตร์',
    physics: 'ฟิสิกส์',
    chemistry: 'เคมี',
    biology: 'ชีววิทยา',
    easy: 'ง่าย',
    medium: 'ปานกลาง',
    hard: 'ยาก',
    next: 'ถัดไป',
    previous: 'ก่อนหน้า',
    finish: 'เสร็จสิ้น',
    score: 'คะแนน',
    timeRemaining: 'เวลาที่เหลือ',
    explanation: 'คำอธิบาย',
    correct: 'ถูกต้อง',
    incorrect: 'ไม่ถูกต้อง',
    quizComplete: 'ทำควิซเสร็จแล้ว!',
    backToHome: 'กลับหน้าหลัก',
    history: 'ประวัติการทำควิซ',
    stats: 'สถิติผลงาน',
    noHistory: 'ยังไม่มีประวัติการทำควิซ เริ่มเรียนรู้เลย!',
    generating: 'กำลังสร้างควิซ AI ของคุณ...',
    loadingMessage: 'AI ของเรากำลังสร้างคำถามเฉพาะสำหรับคุณ...',
    points: 'คะแนน',
    accuracy: 'ความแม่นยำ',
    share: 'แชร์ผลลัพธ์',
    downloadCertificate: 'ดาวน์โหลดเกียรติบัตร',
    retry: 'เริ่มควิซอีกครั้ง',
    generateCard: 'สร้างเกียรติบัตร AI',
    generatingCard: 'กำลังสร้างเกียรติบัตร...',
    cardReady: 'เกียรติบัตรของคุณพร้อมแล้ว!',
    downloadPNG: 'ดาวน์โหลด PNG',
    downloadPDF: 'ดาวน์โหลด PDF',
    saveScoreCTA: 'สมัครสมาชิกเพื่อบันทึกคะแนนนี้อย่างถาวร',
    scoreSaved: 'บันทึกคะแนนลงในโปรไฟล์ของคุณแล้ว!',
    limitReached: 'ครบกำหนดจำนวนรายสัปดาห์แล้ว',
    limitDescription: 'ผู้ใช้งานฟรีสามารถสร้างควิซได้ 3 ครั้งต่อสัปดาห์',
    upgradePro: 'อัปเกรดเป็น Pro เพื่อทำควิซได้ไม่จำกัด',
    quizzesRemaining: 'จำนวนควิซที่เหลือในสัปดาห์นี้',
    monthly: 'รายเดือน',
    annually: 'รายปี',
    bestValue: 'คุ้มค่าที่สุด',
    subscribe: 'สมัครสมาชิกเลย'
  },
  vi: {
    appName: 'Quiz X.ai',
    tagline: 'Làm chủ các môn học với bài trắc nghiệm AI',
    startQuiz: 'Bắt đầu bài kiểm tra',
    selectLanguage: 'Chọn ngôn ngữ',
    selectSubject: 'Chọn môn học',
    selectDifficulty: 'Chọn độ khó',
    mathematics: 'Toán học',
    physics: 'Vật lý',
    chemistry: 'Hóa học',
    biology: 'Sinh học',
    easy: 'Dễ',
    medium: 'Trung bình',
    hard: 'Khó',
    next: 'Tiếp theo',
    previous: 'Quay lại',
    finish: 'Hoàn thành',
    score: 'Điểm số',
    timeRemaining: 'Thời gian còn lại',
    explanation: 'Giải thích',
    correct: 'Chính xác',
    incorrect: 'Sai',
    quizComplete: 'Đã hoàn thành bài kiểm tra!',
    backToHome: 'Quay lại trang chủ',
    history: 'Lịch sử bài kiểm tra',
    stats: 'Thống kê hiệu suất',
    noHistory: 'Chưa có bài kiểm tra nào. Hãy bắt đầu học!',
    generating: 'Đang tạo bài kiểm tra AI...',
    loadingMessage: 'AI của chúng tôi đang biên soạn các câu hỏi dành riêng cho bạn...',
    points: 'Điểm',
    accuracy: 'Độ chính xác',
    share: 'Chia sẻ kết quả',
    downloadCertificate: 'Tải chứng chỉ',
    retry: 'Làm lại bài thi',
    generateCard: 'Tạo chứng chỉ AI',
    generatingCard: 'Đang tạo chứng chỉ của bạn...',
    cardReady: 'Chứng chỉ của bạn đã sẵn sàng!',
    downloadPNG: 'Tải PNG',
    downloadPDF: 'Tải PDF',
    saveScoreCTA: 'Đăng ký để lưu điểm số này vĩnh viễn',
    scoreSaved: 'Đã lưu điểm vào hồ sơ của bạn!',
    limitReached: 'Đã đạt giới hạn tuần',
    limitDescription: 'Người dùng miễn phí chỉ có thể tạo 3 bài kiểm tra mỗi tuần.',
    upgradePro: 'Nâng cấp Pro để không giới hạn bài kiểm tra',
    quizzesRemaining: 'Số bài kiểm tra còn lại trong tuần',
    monthly: 'Hàng tháng',
    annually: 'Hàng năm',
    bestValue: 'Giá tốt nhất',
    subscribe: 'Đăng ký ngay'
  }
};

export const SUBJECTS: Subject[] = ['mathematics', 'physics', 'chemistry', 'biology'];
export const DIFFICULTIES: Difficulty[] = ['easy', 'medium', 'hard'];
export const LANGUAGES: Language[] = ['en', 'km', 'th', 'vi'];
